### ISSUE TITLE
0.7.19 fails to parse CLI options on maco

### ISSUE THREAD

**Issue by antazoey** [executablebooks/mdformat#483]
### Describe the bug

**context**
When I do `mdformat .` after updating to 0.7.19

**expectation**
I expected it to work

**bug**
But instead it crashes out
Here's an error message I ran into...

```
  File "/Users/jules/virtualenvs/ape/lib/python3.12/site-packages/mdformat_pyproject/plugin.py", line 87, in update_mdit
    cli_opts = _reload_cli_opts()
               ^^^^^^^^^^^^^^^^^^
  File "/Users/jules/virtualenvs/ape/lib/python3.12/site-packages/mdformat_pyproject/plugin.py", line 71, in _reload_cli_opts
    arg_parser = mdformat._cli.make_arg_parser(enabled_parserplugins, enabled_codeformatters)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: make_arg_parser() missing 1 required positional argument: 'parser_extensions'

```

```console
$ mdformat README.md
ERROR ...
```

### Reproduce the bug

running on any file, just something with parsing args is failing i think
sorry not using pipx

### List your environment

mdformat 0.7.19 (mdformat_frontmatter 2.0.8, mdformat_tables 0.4.1, mdformat-gfm 0.3.6, mdformat_pyproject 0.0.1)

**Comment by antazoey** [comment]
already an issue there: https://github.com/csala/mdformat-pyproject/issues/2
